baseURL = "https://radish-miyazaki.github.io"
languageCode = "ja-jp"
title = "method_missing(*)"
rssLimit = 20
copyright = "{{ YEAR }} Radish All rights reserved"
minify = false
canonifyurls = true
publishDir = "docs"

[Author]
  name = "radish"

[permalinks]
  posts = "/:year/:month/:day/:filename"
  pages = "/:slug"

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ["html", "json", "rss"]