baseURL = "https://radish-miyazaki.github.io"
languageCode = "ja-jp"
title = "method_missing(*)"
rssLimit = 20
copyright = "2022 Radish All rights reserved"
minify = false
summaryLength = 30

[params]
  description = 'Radish technical blog.'
  images = ['post-cover.png']

[Author]
  name = "radish"

[permalinks]
  posts = "/:filename"
  pages = "/:slug"

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ["html", "json", "rss"]

