baseURL = "https://radish-miyazaki.github.io/"
languageCode = "ja-jp"
title = "method_missing(*)"
rssLimit = 20
copyright = "2022 Radish All rights reserved"
minify = false
canonifyurls = true

[params]
  description = 'This blog is for learning to techs.'
  images = ['post-cover.png']

[Author]
  name = "radish"

[permalinks]
  posts = "/:year/:month/:day/:filename"
  pages = "/:slug"

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ["html", "json", "rss"]

