baseURL = "https://radish-miyazaki.github.io"
languageCode = "ja-jp"
title = "method_missing(*)"
rssLimit = 20
copyright = "Radish All rights reserved"
minify = false

[Author]
  name = "radish"

[permalinks]
  posts = "/:year/:month/:day/:filename"
  pages = "/:slug"

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ["html", "json", "rss"]